### ISSUE TITLE
How can I generate xml file of partial point cloud?

### ISSUE THREAD

**Issue by otsubo** [robotflow-initiative/dipgrasp#1]
Thank you for sharing the code of such a awesome work. 
I could succeeded to reproduce the result of schunk hand. It's quite fast and I felt I'd like to test it on other hand models. 
I'm reading the paper and the source code now. I could not understand how to generate the xml file of hand's partial point cloud.
Did you use external libraries to generate it?
In addition, are there any other points which should I pay attention for?
If you could give me a guidance how to apply it on other hand models, I'm very pleased.

**Comment by SJTUzjy** [comment]
Hi, otsubo, thank you for your interest in our project.
We actually use a Unity script to generate the XML file, but it's only functional in the Unity Editor, so we haven't released it yet. Since you brought it up, we're going to tweak the script and aim to have a release version out by the end of this week.
Also, if you're planning to test on other hand models, there are a few things you should keep in mind:
1.During the initial pose sampling, make sure the palm is directly facing the object. You'll notice that we use different policies for different hands in the init_sample_config function of the AlgoConfig class.
2.The simulator filter won't work with other hand models.
3.Feel free to fine-tune the parameters in the configuration files to enhance performance.

**Comment by SJTUzjy** [comment]
Hi, otsubo.
We've updated our assets to include the XML generator. Additionally, we've added some information about custom hand model adaptation in our README.md.
Hope this helps!

**Comment by otsubo** [comment]
Hi! Thank you for responding so quick and adding READMe.md!
It's so helpful. I'll try it soon and comment here. Thank you so much again.

**Comment by otsubo** [comment]
Sorry for replying so lately. I could generate the xml file for a new hand model. Thank you for your kind guidance!
